### ISSUE TITLE
CONNECT

### ISSUE THREAD

**Issue by 89z** [j0hnsmith/connspy#5]
ConnSpy doesnt seem to handle CONNECT requests that often happen with proxy servers:

https://medium.com/@mlowicki/http-s-proxy-in-golang-in-less-than-100-lines-of-code-6a51c2f2c38c

**Comment by j0hnsmith** [comment]
Hi, can you provide a small example illustrating the problem?

**Comment by 89z** [comment]
@j0hnsmith thanks for the quick reply. I can provide an example. If you dont mind, Im going to lunch and when I get back I can comment the example

**Comment by 89z** [comment]
I think I misunderstood the purpose of this package. I am looking for a proxy for MITM purpose, this seems to not be that. Sorry for the noise.
